# Generated by Django 5.2.3 on 2025-06-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
